#!/bin/bash
# Deploy Mule to server
# Usage: ./scripts/deploy.sh
#
# Deployment steps:
# 1. Pull latest code from git
# 2. Generate build info (version, commit, timestamp) for Flutter client
# 3. Build Flutter web client with SkWasm renderer
# 4. Copy build output to static/ directory
# 5. Generate version.json for /api/version endpoint
# 6. Restart mule service via pm2

set -e

cd "$(dirname "$0")/.."

# Build info
VERSION="1.0.0"
BUILD_TIME=$(date "+%Y-%m-%d %H:%M:00")
GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

echo "=== Mule Deployment ==="
echo ""

# Step 1: Pull latest code
echo "[1/5] Pulling latest code..."
git pull
# Update git commit after pull
GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

# Step 2: Generate build_info.dart for Flutter
echo "[2/5] Generating build info..."
cat > "client/lib/config/build_info.dart" << DART
// Auto-generated build info - DO NOT EDIT
// Generated by scripts/deploy.sh

class BuildInfo {
  static const String version = "$VERSION";
  static const String buildTime = "$BUILD_TIME";
  static const String gitCommit = "$GIT_COMMIT";
}
DART
echo "  v$VERSION ($GIT_COMMIT) @ $BUILD_TIME"

# Step 3: Build Flutter web with SkWasm
echo "[3/5] Building Flutter web (SkWasm)..."
cd client
flutter build web --wasm
cd ..

# Step 4: Copy to static directory
echo "[4/5] Copying build to static/..."
cp -r client/build/web/* static/

# Step 5: Generate version.json for API
echo "[5/5] Generating version.json..."
cat > "static/version.json" << JSON
{"version":"$VERSION","buildTime":"$BUILD_TIME","gitCommit":"$GIT_COMMIT"}
JSON

# Step 6: Restart service
echo ""
echo "Restarting mule service..."
pm2 restart mule

echo ""
echo "=== Deployment Complete ==="
echo "Version: v$VERSION ($GIT_COMMIT)"
echo "Build time: $BUILD_TIME"
